### ISSUE TITLE
All test cases failed and simple cases also failed

### ISSUE THREAD

**Issue by xupeng1231** [sslab-gatech/qsym#102] opened 2022-06-25 15:45 UTC
I strictly follow the instructions in README, and successfully installed qsym in ubuntu(16.04.06/16.04.07), however all test cases (`python -m pytest -n 4`) failed. the scenario is as follow. And I also test a simple case, qsym always return 255.
I doubt that the current installation instructions and source code is not suitable and need update.

The installation steps:
```# disable ptrace_scope for PIN
$ echo 0|sudo tee /proc/sys/kernel/yama/ptrace_scope

# install z3 and system deps
$ ./setup.sh

# install using virtual env
$ virtualenv venv
$ source venv/bin/activate
$ pip install .
```
The partial output of unit test:
```
test_avx2.py:25: AssertionError
------------------------------ Captured log call -------------------------------
DEBUG    qsym.Executor:executor.py:109 Executing timeout -k 5 30 /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/qsym-0OVJz7/qsym-out-0/pin.log -i /home/sentosa/qsym/tests/avx2/vpmulld/input.bin -s 1 -o /tmp/qsym-0OVJz7/qsym-out-0 -- /home/sentosa/qsym/tests/avx2/vpmulld/main
____________ test_functions[/home/sentosa/qsym/tests/avx2/vpshufb] _____________
[gw2] linux2 -- Python 2.7.12 /home/sentosa/qsym/venv/bin/python

target = '/home/sentosa/qsym/tests/avx2/vpshufb'

    def test_functions(target):
        logging.getLogger('qsym.Executor').setLevel(logging.DEBUG)
        # if cpu does not support avx2, then return
        if not 'avx2' in open("/proc/cpuinfo").read():
            return
    
>       assert run_single_test(target)
E       AssertionError: assert False
E        +  where False = run_single_test('/home/sentosa/qsym/tests/avx2/vpshufb')

test_avx2.py:25: AssertionError
------------------------------ Captured log call -------------------------------
DEBUG    qsym.Executor:executor.py:109 Executing timeout -k 5 30 /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/qsym-smZde8/qsym-out-0/pin.log -i /home/sentosa/qsym/tests/avx2/vpshufb/input.bin -s 1 -o /tmp/qsym-smZde8/qsym-out-0 -- /home/sentosa/qsym/tests/avx2/vpshufb/main
______________ test_functions[/home/sentosa/qsym/tests/avx2/vpor] ______________
[gw1] linux2 -- Python 2.7.12 /home/sentosa/qsym/venv/bin/python

target = '/home/sentosa/qsym/tests/avx2/vpor'

    def test_functions(target):
        logging.getLogger('qsym.Executor').setLevel(logging.DEBUG)
        # if cpu does not support avx2, then return
        if not 'avx2' in open("/proc/cpuinfo").read():
            return
    
>       assert run_single_test(target)
E       AssertionError: assert False
E        +  where False = run_single_test('/home/sentosa/qsym/tests/avx2/vpor')

test_avx2.py:25: AssertionError
------------------------------ Captured log call -------------------------------
DEBUG    qsym.Executor:executor.py:109 Executing timeout -k 5 30 /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/qsym-e_55p7/qsym-out-0/pin.log -i /home/sentosa/qsym/tests/avx2/vpor/input.bin -s 1 -o /tmp/qsym-e_55p7/qsym-out-0 -- /home/sentosa/qsym/tests/avx2/vpor/main
____________ test_functions[/home/sentosa/qsym/tests/avx2/vpshufhw] ____________
[gw3] linux2 -- Python 2.7.12 /home/sentosa/qsym/venv/bin/python

target = '/home/sentosa/qsym/tests/avx2/vpshufhw'

    def test_functions(target):
        logging.getLogger('qsym.Executor').setLevel(logging.DEBUG)
        # if cpu does not support avx2, then return
        if not 'avx2' in open("/proc/cpuinfo").read():
            return
    
>       assert run_single_test(target)
E       AssertionError: assert False
E        +  where False = run_single_test('/home/sentosa/qsym/tests/avx2/vpshufhw')

test_avx2.py:25: AssertionError
------------------------------ Captured log call -------------------------------
DEBUG    qsym.Executor:executor.py:109 Executing timeout -k 5 30 /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/qsym-MH8HJ2/qsym-out-0/pin.log -i /home/sentosa/qsym/tests/avx2/vpshufhw/input.bin -s 1 -o /tmp/qsym-MH8HJ2/qsym-out-0 -- /home/sentosa/qsym/tests/avx2/vpshufhw/main
____________ test_functions[/home/sentosa/qsym/tests/avx2/vpshuflw] ____________
[gw0] linux2 -- Python 2.7.12 /home/sentosa/qsym/venv/bin/python

target = '/home/sentosa/qsym/tests/avx2/vpshuflw'

    def test_functions(target):
        logging.getLogger('qsym.Executor').setLevel(logging.DEBUG)
        # if cpu does not support avx2, then return
        if not 'avx2' in open("/proc/cpuinfo").read():
            return
    
>       assert run_single_test(target)
E       AssertionError: assert False
E        +  where False = run_single_test('/home/sentosa/qsym/tests/avx2/vpshuflw')

test_avx2.py:25: AssertionError
------------------------------ Captured log call -------------------------------
DEBUG    qsym.Executor:executor.py:109 Executing timeout -k 5 30 /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/qsym-hdhP_U/qsym-out-0/pin.log -i /home/sentosa/qsym/tests/avx2/vpshuflw/input.bin -s 1 -o /tmp/qsym-hdhP_U/qsym-out-0 -- /home/sentosa/qsym/tests/avx2/vpshuflw/main
_____________ test_functions[/home/sentosa/qsym/tests/avx2/vpxor] ______________
[gw2] linux2 -- Python 2.7.12 /home/sentosa/qsym/venv/bin/python

target = '/home/sentosa/qsym/tests/avx2/vpxor'

    def test_functions(target):
        logging.getLogger('qsym.Executor').setLevel(logging.DEBUG)
        # if cpu does not support avx2, then return
        if not 'avx2' in open("/proc/cpuinfo").read():
            return
    
>       assert run_single_test(target)
E       AssertionError: assert False
E        +  where False = run_single_test('/home/sentosa/qsym/tests/avx2/vpxor')

test_avx2.py:25: AssertionError
------------------------------ Captured log call -------------------------------
DEBUG    qsym.Executor:executor.py:109 Executing timeout -k 5 30 /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/qsym-cj4pU4/qsym-out-0/pin.log -i /home/sentosa/qsym/tests/avx2/vpxor/input.bin -s 1 -o /tmp/qsym-cj4pU4/qsym-out-0 -- /home/sentosa/qsym/tests/avx2/vpxor/main
_____________ test_functions[/home/sentosa/qsym/tests/avx2/vpsrad] _____________
[gw1] linux2 -- Python 2.7.12 /home/sentosa/qsym/venv/bin/python

target = '/home/sentosa/qsym/tests/avx2/vpsrad'

    def test_functions(target):
        logging.getLogger('qsym.Executor').setLevel(logging.DEBUG)
        # if cpu does not support avx2, then return
        if not 'avx2' in open("/proc/cpuinfo").read():
            return
    
>       assert run_single_test(target)
E       AssertionError: assert False
E        +  where False = run_single_test('/home/sentosa/qsym/tests/avx2/vpsrad')

test_avx2.py:25: AssertionError
------------------------------ Captured log call -------------------------------
DEBUG    qsym.Executor:executor.py:109 Executing timeout -k 5 30 /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/qsym-e37AII/qsym-out-0/pin.log -i /home/sentosa/qsym/tests/avx2/vpsrad/input.bin -s 1 -o /tmp/qsym-e37AII/qsym-out-0 -- /home/sentosa/qsym/tests/avx2/vpsrad/main
___________________ test_null_deref_DependencyForest_addNode ___________________
[gw3] linux2 -- Python 2.7.12 /home/sentosa/qsym/venv/bin/python

    def test_null_deref_DependencyForest_addNode():
        target = os.path.join(TESTS_DIR, "regress/null-deref-DependencyForest-addNode")
        assert os.path.exists(target)
    
        output_dir = tempfile.mkdtemp(prefix="qsym-")
        try:
            exe = os.path.join(target, MAIN)
            assert os.path.exists(exe)
    
            q = qsym.Executor([exe], os.path.join(target, "input.bin"), output_dir,
                    argv=["-l", "1"])
            res = q.run(30) # 30 seconds for timeout
>           assert res.returncode == 0
E           assert 255 == 0
E            +  where 255 = <qsym.executor.ExecutorResult object at 0x7fd690bc8cd0>.returncode

test_regress.py:28: AssertionError
------------------------------ Captured log call -------------------------------
DEBUG    qsym.Executor:executor.py:109 Executing timeout -k 5 30 /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/qsym-P4M41w/qsym-out-0/pin.log -i /home/sentosa/qsym/tests/regress/null-deref-DependencyForest-addNode/input.bin -s 1 -o /tmp/qsym-P4M41w/qsym-out-0 -l 1 -- /home/sentosa/qsym/tests/regress/null-deref-DependencyForest-addNode/main
___________________________________ test_dup ___________________________________
[gw0] linux2 -- Python 2.7.12 /home/sentosa/qsym/venv/bin/python

    def test_dup():
        testcases = get_all_testcases("dup")
        # default + 0xdeadbeef
>       assert len(testcases) == 2
E       AssertionError: assert 1 == 2
E        +  where 1 = len(['\x00\x00\x00\x00\n'])

test_schedule.py:79: AssertionError
------------------------------ Captured log call -------------------------------
DEBUG    qsym.Executor:executor.py:109 Executing /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/qsym-zEa2Sq/qsym-out-0/pin.log -i /tmp/qsym-inw2JS -s 1 -o /tmp/qsym-zEa2Sq/qsym-out-0 -b /tmp/qsym-gAvKEU -- /home/sentosa/qsym/tests/schedule/dup/main
____________ test_syscall[/home/sentosa/qsym/tests/syscall/mremap] _____________
[gw2] linux2 -- Python 2.7.12 /home/sentosa/qsym/venv/bin/python

target = '/home/sentosa/qsym/tests/syscall/mremap'

    def test_syscall(target):
        logging.getLogger('qsym.Executor').setLevel(logging.DEBUG)
>       assert run_single_test(target)
E       AssertionError: assert False
E        +  where False = run_single_test('/home/sentosa/qsym/tests/syscall/mremap')

test_syscall.py:21: AssertionError
------------------------------ Captured log call -------------------------------
DEBUG    qsym.Executor:executor.py:109 Executing timeout -k 5 30 /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/sentosa/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/qsym-bSH5pH/qsym-out-0/pin.log -i /home/sentosa/qsym/tests/syscall/mremap/input.bin -s 1 -o /tmp/qsym-bSH5pH/qsym-out-0 -- /home/sentosa/qsym/tests/syscall/mremap/main
========================= 250 failed in 34.64 seconds ==========================

```

**Comment by Vancir** [comment] 2022-06-26 15:36
The problem is caused by this line of code. I modified it to `ADDRINT addr = ctx->ret;` and it can pass all unit tests.

```diff
diff --git a/qsym/pintool/third_party/libdft/syscall_desc.cpp b/qsym/pintool/third_party/libdft/syscall_desc.cpp
index 4514315..d977898 100644
--- a/qsym/pintool/third_party/libdft/syscall_desc.cpp
+++ b/qsym/pintool/third_party/libdft/syscall_desc.cpp
@@ -498,9 +498,8 @@ static void
 postBrkHook(SyscallContext *ctx)
 {
        // brk() return value; in Linux brk returns
-       // the address of the new program break, or
-       // the current value in case of failure
-       ADDRINT addr = ctx->ret;
+       // 0 on success, -1 otherwise
+       ADDRINT addr = ctx->arg[SYSCALL_ARG0];

   if (unlikely(addr == g_memory.brk_end()))
     return;
```

This line of code may be merged from the upstream repo `libdft`.

**Comment by insuyun** [comment] 2022-06-28 00:34
Thank you, @Vancir. That sounds strange. According to the specification, brk() should return status code, not the address.

**Comment by insuyun** [comment] 2022-06-28 00:39
Oh. I found the reason. That patch is incorrect. brk() in glibc returns integer code, but brk() in system call, which is used by QSYM returns address. So the original code is correct.

**Comment by insuyun** [comment] 2022-06-28 00:40
Fixed by 4b7fa3c93d341a015c015fe33b2818160401474e

**Closed by insuyun** 2022-06-28 00:40 UTC

**Comment by Ljfanny** [comment] 2022-11-07 15:06
I also meet this error with same information after the patch.

```
_______________________________________________________________________ test_functions[/qsym/tests/avx2/vpxor] _______________________________________________________________________
[gw111] linux2 -- Python 2.7.12 /usr/bin/python

target = '/qsym/tests/avx2/vpxor'

    def test_functions(target):
        logging.getLogger('qsym.Executor').setLevel(logging.DEBUG)
        # if cpu does not support avx2, then return
        if not 'avx2' in open("/proc/cpuinfo").read():
            return
    
>       assert run_single_test(target)
E       AssertionError: assert False
E        +  where False = run_single_test('/qsym/tests/avx2/vpxor')

test_avx2.py:25: AssertionError
--------------------------------------------------------------------------------- Captured log call ----------------------------------------------------------------------------------
DEBUG    qsym.Executor:executor.py:109 Executing timeout -k 5 30 /usr/local/lib/python2.7/dist-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /usr/local/lib/python2.7/dist-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/qsym-en_ofS/qsym-out-0/pin.log -i /qsym/tests/avx2/vpxor/input.bin -s 1 -o /tmp/qsym-en_ofS/qsym-out-0 -- /qsym/tests/avx2/vpxor/main
______________________________________________________________________ test_functions[/qsym/tests/avx2/vpshufb] ______________________________________________________________________
[gw120] linux2 -- Python 2.7.12 /usr/bin/python

target = '/qsym/tests/avx2/vpshufb'

    def test_functions(target):
        logging.getLogger('qsym.Executor').setLevel(logging.DEBUG)
        # if cpu does not support avx2, then return
        if not 'avx2' in open("/proc/cpuinfo").read():
            return
    
>       assert run_single_test(target)
E       AssertionError: assert False
E        +  where False = run_single_test('/qsym/tests/avx2/vpshufb')

test_avx2.py:25: AssertionError
--------------------------------------------------------------------------------- Captured log call ----------------------------------------------------------------------------------
DEBUG    qsym.Executor:executor.py:109 Executing timeout -k 5 30 /usr/local/lib/python2.7/dist-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /usr/local/lib/python2.7/dist-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/qsym-mcDe8s/qsym-out-0/pin.log -i /qsym/tests/avx2/vpshufb/input.bin -s 1 -o /tmp/qsym-mcDe8s/qsym-out-0 -- /qsym/tests/avx2/vpshufb/main
============================================================================= 250 failed in 5.51 seconds =============================================================================

```

**Comment by Ljfanny** [comment] 2022-11-07 15:10
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609 
kernel 4.15.0-147-generic
Ubuntu 16.04.6 LTS

**Comment by insuyun** [comment] 2022-11-22 08:39
Hi @Ljfanny. Did you run your tests in the tests directory?
